---
title: "model"
author: "YI LIU"
date: "12/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(arsenal)
library(dplyr)
library(MASS)
library(HH)
library(ggpubr)

theme_set(theme_minimal() + theme_bw())
```

```{r,message=FALSE}
lawsuit = 
  read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names()
```

# take the average of 2 years salary

```{r}
lawsuit = 
  lawsuit %>% 
  mutate(
    aveg_sal = (sal94 + sal95)/2,
    lg_aveg_sal = log(aveg_sal)
    )
```

# clean the data and do log transformation

```{r}
lawsuit_clean =
  lawsuit %>% 
  mutate(
    dept = as.factor(dept),
    gender = as.factor(gender),
    clin = as.factor(clin),
    cert = as.factor(cert),
    rank = as.factor(rank),
    dept = recode(dept, 
                  "1"= "bio",
                  "2" = "phys",
                  "3" = "gene",
                  "4" = "ped",
                  "5" = "med", 
                  "6" = "surgery"),
    gender = recode(gender, 
                    "0" = "female",
                    "1" = "male"),
    clin = recode(clin, 
                  "1" = "clinical",
                  "0" = "research"),
    cert = recode(cert, 
                  "0" = "not",
                  "1" = "board"),
    rank = recode(rank, 
                  "1" = "assistant",
                  "2" = "associate",
                  "3" = "full")
  ) 


```


# find confounder

```{r}
fit_gender = lm(lg_aveg_sal ~ gender, data = lawsuit_clean)
summary(fit_gender)
# gender coefficient =0.3853

fit1 = lm(lg_aveg_sal ~ gender + dept, data = lawsuit_clean)
summary(fit1)
anova(fit_gender,fit1)
# adding dept, gender coefficient =0.20521, 46.74%

fit2 = lm(lg_aveg_sal ~ gender + clin, data = lawsuit_clean)
summary(fit2)
anova(fit_gender,fit2)
# adding clin, gender coef = 0.33718, 12.49%

fit3 = lm(lg_aveg_sal ~ gender + cert, data = lawsuit_clean)
summary(fit3)
anova(fit_gender,fit3)
# adding cert, gender coef = 0.33285, 13.61%

fit4 = lm(lg_aveg_sal ~ gender + prate, data = lawsuit_clean)
summary(fit4)
anova(fit_gender,fit4)
# adding prate, gender coef = 0.2518, 34.65%

fit5 = lm(lg_aveg_sal ~ gender + exper, data = lawsuit_clean)
summary(fit5)
anova(fit_gender,fit5)
#adding exper, gender coef = 0.30755,20.18%

fit6 = lm(lg_aveg_sal ~ gender + rank, data = lawsuit_clean)
summary(fit6)
anova(fit_gender,fit6)
#adding rank, gender coef = 0.34948, 9.3%

confounder_fit = lm(lg_aveg_sal ~ gender + dept + clin + cert + prate + exper + rank, data = lawsuit_clean)
summary(confounder_fit)

vif(confounder_fit)
#the vif of prate is larger than 10 ,implying serious collinearity, then we drop prate

conf_final_fit = lm(lg_aveg_sal ~ gender + dept + clin + cert + exper+ rank, data = lawsuit_clean)
summary(conf_final_fit)


```

# find interaction

```{r}
# gender may have interaction with exper
exper_fig =
  lawsuit_clean %>% 
  ggplot(aes(x = exper, y = lg_aveg_sal)) +geom_point(aes(color = gender)) +geom_smooth(method = "lm", aes(color = gender))
# gender may not have interaction with prate
prate_fig =
  lawsuit_clean %>% 
  ggplot(aes(x = prate, y = lg_aveg_sal)) +geom_point(aes(color = gender)) +geom_smooth(method = "lm", aes(color = gender))
```



```{r}
clin_fig = 
lawsuit_clean %>% 
ggplot(aes(x = clin, y = lg_aveg_sal, fill = gender)) +
  geom_boxplot() +
  xlab("clin") +
  ylab("Lg(average salary)")

cert_fig = 
lawsuit_clean %>% 
ggplot(aes(x = cert, y = lg_aveg_sal, fill = gender)) +
  geom_boxplot() +
  xlab("cert") +
  ylab("Lg(average salary)")

rank_fig = 
lawsuit_clean %>% 
ggplot(aes(x = rank, y = lg_aveg_sal, fill = gender)) +
  geom_boxplot() +
  xlab("rank") +
  ylab("Lg(average salary)")
  
dept_fig = 
lawsuit_clean %>% 
ggplot(aes(x = dept, y = lg_aveg_sal, fill = gender)) +
  geom_boxplot() +
  xlab("department") +
  ylab("Lg(average salary)")

gender_fig = 
lawsuit_clean %>% 
ggplot(aes(x = gender, y = lg_aveg_sal, fill = gender)) +
  geom_boxplot() +
  xlab("gender") +
  ylab("Lg(average salary)")

ggarrange(exper_fig,prate_fig, dept_fig, clin_fig, cert_fig, rank_fig, gender_fig,ncol = 3, nrow = 3)
```


```{r}
inter1 = lm(lg_aveg_sal ~ gender * dept + clin + cert + exper + rank , data = lawsuit_clean)
summary(inter1)
#there is no interaction b/w gender and dept

inter2 = lm(lg_aveg_sal ~ gender*clin + dept  + cert + exper + rank , data = lawsuit_clean)
summary(inter2)

#there is no interaction b/w gender and clin

inter3 = lm(lg_aveg_sal ~ gender*cert + clin + dept + exper +rank, data = lawsuit_clean)
summary(inter3)

# there is no interaction b/w gender and cert

inter4 = lm(lg_aveg_sal ~ gender*exper + cert + clin + dept + rank , data = lawsuit_clean)
summary(inter4)

# there is interaction b/w gender and exper

inter5 = lm(lg_aveg_sal ~ gender*prate + dept + clin + cert + exper +rank , data = lawsuit_clean)
summary(inter5)

# there is no interaction b/w gender and prate

inter6 = lm(lg_aveg_sal ~ gender*rank + dept + clin + cert + exper , data = lawsuit_clean)
summary(inter6)
# there is interaction b/w gender and rank

```

# stratify

##stratify rank
```{r}
#assistant
assistant_df =
  lawsuit_clean %>%
  filter(id != 184) %>% 
  filter(rank == "assistant")
assistant_fit = lm(lg_aveg_sal ~ gender+exper + dept + clin +cert, data = assistant_df)
summary(assistant_fit)


#associate
associate_df =
  lawsuit_clean %>% 
  filter(rank == "associate")
associate_fit = lm(lg_aveg_sal ~ gender+exper + dept + clin +cert, data = associate_df)
summary(associate_fit)



#full professor

full_df =
  lawsuit_clean %>% 
  filter(rank == "full")
full_fit = lm(lg_aveg_sal ~ gender+exper + dept + clin +cert, data = full_df)
summary(full_fit)


```

## stratify exper using 10

```{r}
experlarge_df = 
  lawsuit_clean %>% 
  filter(exper >= 10)
experlarge_fit = lm(lg_aveg_sal ~ gender+rank + dept + clin +cert, data = experlarge_df)
summary(experlarge_fit)


expersmall_df = 
  lawsuit_clean %>% 
  filter(exper < 10)
expersmall_fit = lm(lg_aveg_sal ~ gender+rank + dept + clin +cert , data = expersmall_df)
summary(expersmall_fit)
```




```{r}
final1_fit = lm(lg_aveg_sal ~ dept + clin + cert + gender*exper + gender * rank, data = lawsuit_clean)
summary(final1_fit)


par(mfrow = c(2, 2))
plot(final1_fit)

step(final1_fit, direction = 'backward')
```


# potential outliers

```{r}
lawsuit_nooutlier = 
  lawsuit_clean %>% 
  filter(id != 184)

final2_fit = lm(lg_aveg_sal ~ dept + clin + cert + gender*exper +gender*rank, data = lawsuit_nooutlier)
summary(final2_fit)
par(mfrow = c(2, 2))
plot(final2_fit)
```


