---
title: "p8130_finalproject"
author: "YI LIU"
date: "12/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(arsenal)
library(dplyr)
```

```{r,message=FALSE}
lawsuit = 
  read_csv("./Lawsuit.csv") %>% 
  janitor::clean_names()
```

# take the average of 2 years salary

```{r}
lawsuit = 
  lawsuit %>% 
  mutate(
    aveg_sal = (sal94 + sal95)/2
    )
```

# clean the data and do log transformation

```{r}
lawsuit_clean =
  lawsuit %>% 
  select(-id, -sal94, -sal95) %>% 
  mutate(lg_aveg_sal = log(aveg_sal),
    dept = as.factor(dept),
    gender = as.factor(gender),
    clin = as.factor(clin),
    cert = as.factor(cert),
    rank = as.factor(rank),
    dept = recode(dept, 
                  "1"= "bio",
                  "2" = "phys",
                  "3" = "gene",
                  "4" = "ped",
                  "5" = "med", 
                  "6" = "surgery"),
    gender = recode(gender, 
                    "0" = "female",
                    "1" = "male"),
    clin = recode(clin, 
                  "1" = "clinical",
                  "0" = "research"),
    cert = recode(cert, 
                  "0" = "not",
                  "1" = "board"),
    rank = recode(rank, 
                  "1" = "assitent",
                  "2" = "associate",
                  "3" = "full")
  )


```

# model 1 all covariate

```{r}
fit1 = lm(lg_aveg_sal ~ ., data = lawsuit_clean)
summary(fit1)
```




